version: '3'

services:
  app:
    build: .
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    ports:
      - 3000:3000
    depends_on:
      - db
      - kafka
    volumes:
      - .:/usr/src
      - /usr/src/tmp
  db:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
      POSTGRES_DB: rails-kafka_development
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.178.21
      KAFKA_CREATE_TOPICS: test:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
