version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src
  db:
    image: postgres:10.5-alpine
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.178.21
      KAFKA_CREATE_TOPICS: test:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
