version: '3'

services:
  app:
    build: .
    container_name: rails-app
    tty: true
    stdin_open: true
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/usr/src
      - /usr/src/tmp
  db:
    image: postgres:10.5-alpine
    container_name: rails-db
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
      POSTGRES_DB: rails-kafka_development
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: confluentinc/cp-schema-registry:5.0.0
    container_name: registry
    depends_on:
      - kafka
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  control-center:
    image: confluentinc/cp-enterprise-control-center:5.0.0
    container_name: control-center
    environment:
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 2
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8082
    ports:
      - 9021:9021
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - /tmp/control-center/data:/var/lib/confluent-control-center
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
