default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  host: db

development:
  <<: *default
  database: rails-kafka_development

test:
  <<: *default
  database: rails-kafka_test

production:
  <<: *default
  database: rails-kafka_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
